version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: auth_database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 460461
      POSTGRES_DB: auth_database
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
