services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 460461
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

